name: Java CI with Maven
on:
  push:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn compile
      - name: Test with Maven
        run: mvn test
      - name: Package with Maven
        run: mvn package
      - run: mkdir artifact && cp target/*.jar artifact
      - uses: actions/upload-artifact@v2
        with:
          name: api-testing-${{ github.run_number }}.jar
          path: target/*.jar
      - name: Rename file
        run: mv target/*.jar target/api-testing-${{ github.run_number }}.jar
      - name: Upload to S3 as artifact
        uses: medlypharmacy/s3-artifacts-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_S3_ACCESS_ID}}
          aws_secret_access_key: ${{ secrets.AWS_S3_ACCESS_KEY}}
          aws_s3_bucket_name: ${{ secrets.AWS_S3_BUCKET_NAME }}
          source_path: 'target/api-testing-${{ github.run_number }}.jar'
          exclude_repo_from_destination_path: true
          destination_path: 'int-test-artifacts/api-testing-${{ github.run_number }}.jar'
